export const ButtonList = [
    {label: 'Home', link: '/', icon: 'home', newTab: false},
    {label: 'About', link: '/about', icon: 'info', newTab: false},
    {label: 'Projects', link: '/projects', icon: 'Projects', newTab: false},
    {label: 'Contact', link: '/contact', icon: 'contact', newTab: false},
    {label: 'Github', link: 'https://github.com/johnny-m-lee', icon: 'github', newTab: true},
    {label: 'LinkedIn', link: 'https://www.linkedin.com/in/johnny-lee-1000/', icon: 'linkedin', newTab: true},
    {label: 'Resume', link: 'https://drive.google.com/file/d/17Z7Z6077707625077777777777777777/view?usp=sharing', icon: 'resume', newTab: true},
    {label: 'x', link: 'https://twitter.com/johnny_m_lee', icon: 'twitter', newTab: true},
];

export const ProjectData = [
    {
        hading: 'CodeKing',
        subTitle: '(Problem solving)',
        paraGraph: 'Welcome to CodeKing, where coding challenges await and solutions reign supreme! Dive into a realm of problem-solving prowess, where every line of code brings you closer to mastery. Join us on this epic journey of discovery and triumph. Are you ready to conquer the code?',
        isRight: false,
        image: '/images/codeKing.png',
        link: 'https://github.com/Bapparajsk/codeking',
        buttonList: ['next.js', 'express.js', 'node.js', 'mongoDB', 'mongoose', 'tailwindcss',],
        color: '1D24CA',
        top: 30,
    },
    {
        hading: 'News App',
        subTitle: '(The Insight Network)',
        paraGraph: 'Welcome to I-News, your go-to source for up-to-the-minute updates and insightful analysis. Stay informed with our curated selection of top stories spanning global affairs, technology, business, and more. Dive deeper into the headlines that matter and explore diverse perspectives, all in one convenient place.',
        isRight: true,
        image: '/images/news.png',
        link: 'https://github.com/Bapparajsk/Inews',
        buttonList: ['react.js', 'javascript', 'tailwindcss', 'api'],
        color: '525CEB',
        top: 40,
    },
    {
        hading: 'Music.io',
        subTitle: '(Entertainment)',
        paraGraph: 'Welcome to our music app, where tunes meet tech. Discover, groove, repeat. Dive into curated playlists, find new favorites, and let the beats guide your journey.',
        isRight: false,
        image: '/images/music.png',
        link: 'https://github.com/Bapparajsk/music.io',
        buttonList: ['html', 'javascript', 'css',],
        color: 'D862BC',
        top: 0,
    },
    {
        hading: 'Calculator',
        subTitle: '(Productivity)',
        paraGraph: 'Welcome to our Calculator web app, where precision meets simplicity. Whether you\'re crunching numbers for work or school, our intuitive interface makes math effortless. Experience the convenience of mathematics at your fingertips, right here.',
        isRight: true,
        image: '/images/calculator.png',
        link: 'https://github.com/Bapparajsk/calculator',
        buttonList: ['html', 'javascript', 'css',],
        color: '865DFF',
        top: -110,
    },
]
