import { Inter } from "next/font/google";
import "./globals.css";
import "./fonts.css";
import {Providers} from "@/app/Providers";
import {FireFliesBackground} from "@/components/FireFliesBackground";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body className={clsx(inter.className, 'font-inter')}>
      <Providers>
          {children}
          <FireFliesBackground/>
      </Providers>
      </body>
    </html>
  );
}
